### ISSUE TITLE
Octave doesn't find python

### ISSUE THREAD

**Issue by Landgraf132** [octave-snap/octave-snap#17]
Python installed in system.
OS: Kubuntu 19.10

```
>> pkg load symbolic
>> syms x
Symbolic pkg v2.8.0: sh: 1: python: not found
error: Cannot run the Python executable "python"
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 61 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
>> sympref diagnose

Symbolic package diagnostics
============================

Python and SymPy are needed for most features of the Symbolic package.

The Python interpreter is currently: "python".

Computers may have more than one Python interpreter installed.  If you
need to, you can select a different one using the PYTHON environment
variable (see "help sympref").  For example, to use Python 3, try
    setenv PYTHON python3
    sympref reset

Attempting to run python -c "print(\"Python says hello\")"

sh: 1: python: not found
status =  127
output =

Unfortunately, that command failed!
We expected to see "status = 0" and "output = Python says hello".

  * Is there an error message above?

  * Do you have Python installed?

  * Please try using "setenv" as described above.

  * Most systems search the PATH environment when looking for commands.
    Your path seems to be:

/snap/octave/9/usr/sbin:/snap/octave/9/usr/bin:/snap/octave/9/sbin:/snap/octave/9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/octave/9/usr/libexec/octave/5.1.0/site/exec/x86_64-pc-linux-gnu:/snap/octave/9/usr/libexec/octave/api-v53/site/exec/x86_64-pc-linux-gnu:/snap/octave/9/usr/libexec/octave/site/exec/x86_64-pc-linux-gnu:/snap/octave/9/usr/libexec/octave/5.1.0/exec/x86_64-pc-linux-gnu:/snap/octave/9/usr/bin
```

**Comment by Landgraf132** [comment]
octave             5.1.0                       9       edge    octave-snap✓  -

**Comment by mtmiller** [comment]
Did you try the advice in the `sympref diagnose` output that you pasted?

    setenv PYTHON python3

**Comment by mtmiller** [comment]
Closing since Octave does find `python3` in the snap /usr/bin directory. The next symbolic package release will use `python3` by default.

There is the remaining issue of SymPy not being installed by default in the snap environment. If someone wants to open an issue about that, that would be a valid enhancement to look at.

**Comment by Landgraf132** [comment]
> Did you try the advice in the `sympref diagnose` output that you pasted?
> 
> ```
> setenv PYTHON python3
> ```
This is partly solved my problem.


```
setenv PYTHON python3
>> syms x
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'
error: Python cannot import SymPy: have you installed SymPy?
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 123 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13

```

sympref diagnose 

Python version
--------------

```
Let's check what version of Python we are calling...

Attempting to run /usr/bin/python3 -c "import sys; print(sys.version)"

status = 0
output = 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
```

But in my system python (debian 9)

```
/usr/bin/python3 -c "import sys; print(sys.version)"
3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
```
As I understand it, the versions of python in the package and in the system are different. I can’t install python packages in snap. Is it possible to forward a system python to a snap package?

**Comment by mtmiller** [comment]
Right, there is no way for a strictly confined snap to see system programs or other resources. So the only Python is what is available inside the `core18` base snap, and what we may choose to bundle in the Octave snap image. You are welcome to open a new issue about including python3-sympy in the Octave snap.

Or, yes you can install Python packages in your snap home directory, for example

    snap run --shell octave
    PATH=/snap/octave/current/usr/bin:$PATH
    curl https://bootstrap.pypa.io/get-pip.py | python3 - --user
    python3 -m pip install --user sympy
    exit
    snap run octave

And in Octave, this works for me now

    >> setenv PYTHON python3
    >> pkg load symbolic
    >> syms x

**Comment by mtmiller** [comment]
Or entirely at the Octave prompt:

    >> setenv PYTHON python3
    >> system ('curl https://bootstrap.pypa.io/get-pip.py | $PYTHON - --user');
    >> system ('$PYTHON -m pip install --user sympy');
    >> pkg load symbolic
    >> syms x
