### ISSUE TITLE
Unable to use virtualenv Python with symbolic package when using Snap

### ISSUE THREAD

**Issue by kwanlowe** [octave-snap/octave-snap#31]
Hello:

I am adding this issue per: https://octave.1599824.n4.nabble.com/Octave-unable-to-find-python-when-using-symbolic-toolbox-tt4695912.html#a4695924

Summary:
On Ubuntu and Linux Mint systems, Octave package from the --beta channel fails to load the symbolic package.

Snap package was installed with: snap install --beta octave
I created a new user for testing (username tester).

```
$ snap run octave
No protocol specified
octave: unable to open X11 DISPLAY
octave: disabling GUI features
GNU Octave, version 5.1.0
Copyright (C) 2019 John W. Eaton and others.
[snip]
```

At the octave prompt, I install the symbolic package:
```
octave:1> pkg install -forge symbolic
warning: creating installation directory /home/tester/snap/octave/21/octave
warning: called from
    install at line 30 column 5
    pkg at line 441 column 9
For information about changes from previous versions of the symbolic package, run 'news sy
mbolic'.
octave:2> pkg load symbolic
octave:3> syms x
Symbolic pkg v2.8.0: sh: 1: python: not found
error: Cannot run the Python executable "python"
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 61 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```
I tried setting the python version to the one available on the host (i.e., the host machine, not the snap container):

```
octave:3> setenv PYTHON /usr/bin/python
octave:4> syms x
Symbolic pkg v2.8.0: sh: 1: /usr/bin/python: not found
error: Cannot run the Python executable "/usr/bin/python"
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 61 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```
The "python" name itself doesn't exist but I can see python3:
```
octave:4> unix("which python")

ans =  1
octave:5> unix("which python3")
/usr/bin/python3

ans = 0
```
I tried using this path:

```
octave:6> setenv PYTHON /usr/bin/python3
octave:7> syms x
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'
error: Python cannot import SymPy: have you installed SymPy?
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 123 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```
I also tried setting PYTHON to python3 with same result:
```
octave:15> setenv PYTHON python3
octave:16> syms x
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'
error: Python cannot import SymPy: have you installed SymPy?
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 123 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
octave:16> 
```

OK.. SymPy itself is not installed in the Snap container.  
I tried next to use my local Python virtualenv (Python 3.6.9).  Enabling this virtual env creates the python, python3 and python3.6 links to the same binary in ~/bin/p36/bin. I was unable to give the snap access to this path, unfortunately.

```
(p36) $ pip list|grep sympy
sympy         1.5.1  
(p36) $ which python
/home/tester/bin/p36/bin/python
(p36) $ 
```
And testing this:

```
octave:9> unix("pwd")
/home/tester
ans = 0
octave:10> setenv PYTHON /home/tester/bin/p36/bin/python
octave:11> syms x
Symbolic pkg v2.8.0: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sympy'
error: Python cannot import SymPy: have you installed SymPy?
    Try "sympref diagnose" for more information.
error: called from
    assert_have_python_and_sympy at line 123 column 7
    python_ipc_popen2 at line 79 column 5
    python_ipc_driver at line 59 column 15
    python_cmd at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```

Next, I tried installing via the Snap pip:

```
octave:11> unix("pip list")
sh: 1: pip: not found

ans =  127
octave:12> unix("python -m pip list")
sh: 1: python: not found

ans =  127
octave:13> unix("python3 -m pip list")
/usr/bin/python3: No module named pip

ans =  1
```

Ultimately this may be user error on my part, but just not sure of how to actually get the sympy package installed  in the Snap container, or more preferably, allow the snap to use a virtualenv in my home directory.

From a solution standpoint, I have occasionally used packages that require a C compiler (e.g., some of the Arduino tools) so a general approach would be much appreciated.

Thanks so much,
Kwan

**Comment by kwanlowe** [comment]
Forgot to add this  additional info:
```
octave:16> getenv("PATH")
ans = /snap/octave/21/usr/sbin:/snap/octave/21/usr/bin:/snap/octave/21/sbin:/snap/octave/21/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/octave/21/libexec/octave/5.1.0/site/exec/x86_64-pc-linux-gnu:/snap/octave/21/libexec/octave/api-v53/site/exec/x86_64-pc-linux-gnu:/snap/octave/21/libexec/octave/site/exec/x86_64-pc-linux-gnu:/snap/octave/21/libexec/octave/5.1.0/exec/x86_64-pc-linux-gnu:/snap/octave/21/bin
```

SymPy is also installed on the host system (both versions):

```
[kwan@exeter ~]$ sudo dpkg -l|grep sympy
ii  python-sympy                                                1.1.1-5                                                     all          Computer Algebra System (CAS) in Python
ii  python3-sympy                                               1.1.1-5                                                     all          Computer Algebra System (CAS) in Python (Python3)
```

**Comment by mtmiller** [comment]
Thank you for this incredibly detailed issue. There's a lot going on here, I'll reply in pieces to the various parts I see, and maybe we can split it up into a few smaller issues.

> octave:2> pkg load symbolic
> octave:3> syms x
> Symbolic pkg v2.8.0: sh: 1: python: not found
> error: Cannot run the Python executable "python"
>     Try "sympref diagnose" for more information.

The first problem here has already been fixed, see https://github.com/cbm755/octsympy/issues/999. The next version of the symbolic package will automatically use `python3` by default.

**Comment by mtmiller** [comment]
> OK.. SymPy itself is not installed in the Snap container.

This is a legit feature request, add SymPy to the Snap installation so it's found and works out of the box. We already have that in Octave on Flathub, so should be done for Snap as well.

**Comment by mtmiller** [comment]
> I tried next to use my local Python virtualenv (Python 3.6.9). Enabling this virtual env creates the python, python3 and python3.6 links to the same binary in ~/bin/p36/bin. I was unable to give the snap access to this path, unfortunately.
[…]
> more preferably, allow the snap to use a virtualenv in my home directory.

Yeah, I agree this should be allowed, may be a bug or may need some extra `PATH` or `PYTHONPATH` or other variables set.

**Comment by mtmiller** [comment]
> Next, I tried installing via the Snap pip:

Yeah, pip is not installed in the Snap filesystem. We could add it, would allow users to install packages with the `--user` option, if that would be helpful. Separate feature request.

**Comment by mtmiller** [comment]
Let's make this issue be about how to get your virtualenv working with the Octave Snap, since that gives users the most flexibility. I'll try it myself a little bit later and see if I can reproduce the problem.

**Comment by mtmiller** [comment]
> I have occasionally used packages that require a C compiler

This is probably #1.

**Comment by kwanlowe** [comment]
Thanks Mike! Getting virtualenv working would be wonderful. Please do let me know if you need any tests run. I have Ubuntu, Mint, CentOS, RHEL8 and some other test systems available.

**Comment by mtmiller** [comment]
Will do. Feel free to open additional issues for

- include sympy in snap filesystem so that symbolic works with /usr/bin/python3
- include pip in snap filesystem so that `pip` and/or `python3 -m pip` work

I'll get to it later if you don't.

**Comment by mtmiller** [comment]
Ok, I can reproduce, can you verify that the error is the same for you?

```
$ /snap/bin/octave
>> setenv PYTHON /home/mike/sympyenv/bin/python3
>> pkg load symbolic
>> syms x
Symbolic pkg v2.8.0: /home/mike/sympyenv/bin/python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mike/sympyenv/bin/python3)
/home/mike/sympyenv/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/mike/sympyenv/bin/python3)
error: Cannot run the Python executable "/home/mike/sympyenv/bin/python3"
    Try "sympref diagnose" for more information.
```

Here's the underlying error

```
$ snap run --shell octave
$ ldd /home/mike/sympyenv/bin/python3
/home/mike/sympyenv/bin/python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/mike/sympyenv/bin/python3)
/home/mike/sympyenv/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/mike/sympyenv/bin/python3)
        linux-vdso.so.1 (0x00007ffee0d32000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb027ecb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb027cac000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb027aa8000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fb0278a5000)
        libexpat.so.1 => /snap/octave/21/lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb027673000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb027456000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb0270b8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb0282bc000)
```

This is essentially the same error you would get building any program on CentOS 8 and trying to run it on Ubuntu 18.04. The Python in my virtualenv is from Debian testing, and is linked against glibc 2.29, but the Snap confined filesystem (based on Ubuntu 18.04) has glibc 2.27.

**Comment by kwanlowe** [comment]
Interesting... So if I'm understanding this correctly, I'd need to either create a 2.27 glibc environment or possibly install in the snap environment (possibly as a virtualenv in the writable space or in the snap system area)?   I wonder if there's a snap base environment that can be used?   I'll take a shot at possibling installing the pip module in the user area based on the snap python. I'll need to play with some environment vars to override this but may work.  Thanks for your efforts on this.

**Comment by kwanlowe** [comment]
Mike:  Give me a couple hours to get back to you on reproducing that error. I thought I could quickly run it from this CentOS system but getting a lot of other errors relating to snap. I don't want to pollute the thread here with what could be unrelated.

**Comment by kwanlowe** [comment]
I put together a kludgey test harness here: git@github.com:kwanlowe/octave_tester.git

Attachhed are results running against a CentOS 8 system.

[Test_Results.zip](https://github.com/octave-snap/octave-snap/files/4263614/Test_Results.zip)

**Comment by mtmiller** [comment]
I'm not sure what to look at in the test results, but yes, using a virtualenv created on a glibc 2.27 system should get this working. Basically any external programs that you call out to from the snapped Octave need to be compatible with Ubuntu 18.04.

And yes, an alternative would be to install pip with `--user` and then install SymPy, or make a virtualenv derived from the snap base /usr/bin/python3.6.

**Comment by mtmiller** [comment]
This creates a virtualenv that works for me with the Octave snap, by using the Python 3.6 that is part of the `core18` base snap

    virtualenv --python=/snap/core18/current/usr/bin/python3.6 ~/sympyenv
    . ~/sympyenv/bin/activate
    pip install -U sympy

Is that a viable solution here?

**Comment by kwanlowe** [comment]
I think that may  be getting closer. I installed a virtualenv using the snap python but getting some core dumps. I'll play around with the locale settings when I get to a place I can debug.  Thanks again for your efforts on this..

```
Attempting to run /home/kwan/bin/python_venv/p36_octave/bin/python3 -c "print(\"Python says hello\")"

Fatal Python error: Py_Initialize: Unable to get the locale encoding
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
PermissionError: [Errno 13] Permission denied: '/home/kwan/bin/python_venv/p36_octave/lib/python3.6/encodings/__init__.py'
Aborted (core dumped)
status =  134
output =
```

**Comment by mtmiller** [comment]
Any progress? I don't get this locale encoding error when I test this here. Permission denied error, was the virtualenv created by a different user account? If this is CentOS / RHEL / Fedora, are SELinux permissions playing into this somehow? Does your audit system log show anything useful?

**Comment by kwanlowe** [comment]
On Mon, Mar 2, 2020 at 7:26 PM Mike Miller <notifications@github.com> wrote:
>
> Any progress? I don't get this locale encoding error when I test this here. Permission denied error, was the virtualenv created by a different user account? If this is CentOS / RHEL / Fedora, are SELinux permissions playing into this somehow? Does your audit system log show anything useful?

Mike:
I was working on this yesterday and ran into the GLIBC errors you'd
seen previously. I tried with various options on virtualenv to do the
copy (system-site-packages, copy, etc.) and setting LD_LIBRARY_PATH to
include the Snap lib64 and lib path. This ended in core dump messages.
I've haven't pulled the core file into gdb yet but will try again
tonight.   I have disabled Selinux with a "setenforce 0" on the test
system. In all cases I am building and running with the "vagrant" user
under a CentOS 8 box (updated during the test).

If you do have access to a Vagrant capable system, I did create a test
harness at https://github.com/kwanlowe/octave_tester.git.  WHen I
reach the office, I will push some updated cases that set
LD_LIBRARY_PATH, copy the LIBC .so directly to the home virtualenv.
I'll also try running as root in cases are some Unix permissions
outside of selinux.

Thanks,
Kwan



-- 
"Don't be lazy. Do the thing. Do it properly."  - Simone Giertz

**Comment by mtmiller** [comment]
It looks to me like your test harness is only creating virtualenvs using /usr/bin/python3. We already know that's not going to work and why, so not worth pursuing that much further.

I still think the best and most reliable approach is to use `--python=/snap/core18/current/usr/bin/python3`, or `snap run --shell octave -c "python3 -m venv"`, start with one of those and try variants from there.

**Comment by kwanlowe** [comment]
On Tue, Mar 3, 2020 at 1:53 PM Mike Miller <notifications@github.com> wrote:
>
> It looks to me like your test harness is only creating virtualenvs using /usr/bin/python3. We already know that's not going to work and why, so not worth pursuing that much further.

> I still think the best and most reliable approach is to use --python=/snap/core18/current/usr/bin/python3, or snap run --shell octave -c "python3 -m venv", start with one of those and try variants from there.

Yes, agreed. These are just from the first tests.. I had also tried
installing the python venv based on the snap, but was getting core
dump errors. The full test is not yet fully coded, but I did run from
my local environment (a Linux Mint laptop vs CentOS).  To not
introduce any other noise, I'd prefer to run it from the test harness
because the state of my Mint laptop is not pristine. I'll write and
upload these cases once I can get to the system (it's at home so I
don't have access from the office).


-- 
"Don't be lazy. Do the thing. Do it properly."  - Simone Giertz

**Comment by kwanlowe** [comment]
OK, I added a test against the Snap python and ... It worked!

There are a couple caveats.. CentOS drops the /snap filesystem at /var/lib/snap instead, so a SymLink needs to be created for things to work right. A Google search indicated this was only needed for classic confinement, but it looks like there are other bits of code that look specifically for a /snap path.

This is the ansible setup code: 
```
    - name: "Setup virtualenv against snap python"
      command: "{{ item }}"
      with_items:
        - "virtualenv --python=/snap/core18/current/usr/bin/python3 ~/python_venv/p3_snap"
        - "~/python_venv/p3_snap/bin/python3 -m pip install sympy"
```

This is the octave script:
```
curPath=getenv("PATH")
newPath=strcat("/home/vagrant/python_venv/p3_snap/bin/:", curPath)
setenv("PATH", newPath)
setenv("PYTHON", "/home/vagrant/python_venv/p3_snap/bin/python3")
pkg install -forge symbolic
pkg load symbolic 
```
I pushed the test code up to my git repo if you want to run it.

Mike.. thanks for your persistence in getting this resolved. It allows me to run on my preferred workstation and saves me a fair amount of work.

**Comment by mtmiller** [comment]
Great, glad it works. Please continue to find and report bugs if you're interested in helping to improve this Snap distribution of Octave.
