### ISSUE TITLE
miscellaneous package install error: unable to find ncurses library headers

### ISSUE THREAD

**Issue by fletcheb** [octave-snap/octave-snap#46]
When trying to install octave forge package "miscellaneous", the following occurs:

>> pkg install -forge miscellaneous
configure: error: Unable to find ncurses library headers.
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking term.h usability... no
checking term.h presence... no
checking for term.h... no
checking termcap.h usability... no
checking termcap.h presence... no
checking for termcap.h... no
checking ncurses/termcap.h usability... no
checking ncurses/termcap.h presence... no
checking for ncurses/termcap.h... no

pkg: error running the configure script for miscellaneous.
error: called from
    configure_make at line 82 column 9
    install at line 190 column 7
    pkg at line 441 column 9
>>

**Comment by mtmiller** [comment]
Confirmed, and looks like an easy fix, PR to fix this welcome.
