### ISSUE TITLE
Snap path can't find unzip

### ISSUE THREAD

**Issue by thalesmaoa** [octave-snap/octave-snap#47]
I'm using io package.
```
pkg -forge install io
```

When I try to use osdwrite it throws an error.

```
Unzip failed with error 127
```

Since it doesn't know system path, it can't find unzip.

It is related to #17. Is there a way to add /usr/bin to path?
It solve the [bug](http://savannah.gnu.org/bugs/?56454) for windows users.

**Comment by mtmiller** [comment]
As always, there is no way for a confined snap to have access to the system /usr/bin. However, we can add unzip and zip to the snap bundle.

**Comment by nworbneb** [comment]
Is there a workaround for this?  I'm not really familiar with the specifics of snap packages, but is it possible to copy the unzip binary somewhere to make this work?  Octave is rather broken for me as it stands.

**Comment by mtmiller** [comment]
The easiest workaround would probably be to fix this by including those programs in the snap. And we will readily accept a PR to do just that.
