### ISSUE TITLE
Access denied to hidden directory in real home directory (~/.wine)

### ISSUE THREAD

**Issue by thalesmaoa** [octave-snap/octave-snap#48]
I have mfiles inside my Documents/ folder.

```
snap connect octave:home
```
Then I open octave.
When I try to access my home folder, i get access denied.

I tried with octave open. I can have access folder. After

```
addpath("/home/user/Documents/mfiles")
```

it just can't find my functions.

**Comment by mtmiller** [comment]
It works for me, possibly due to strict AppArmor confinement settings on Ubuntu. But as far as I can tell from the docs, the home slot should make that work. Suggestions or fixes welcome.

**Comment by mtmiller** [comment]
I can't reproduce this in an Ubuntu 18.04 VM. Any further details on how to trigger this error?

**Comment by thalesmaoa** [comment]
> I can't reproduce this in an Ubuntu 18.04 VM. Any further details on how to trigger this error?

Sorry. I'm using Ubuntu 20 LTS Focal Fossa

**Comment by mtmiller** [comment]
I also can't reproduce in a fresh Ubuntu 20.04 VM. Anything further you can suggest to trigger this?

**Comment by thalesmaoa** [comment]
My miles are imported from:

`addpath("/home/ubuntu/.wine/drive_c/femm42/mfiles");`

I've double checked permissions inside .wine folder and my user is the owner, but it can't see beyond .wine.

If you can't reproduce it, please, let me know so I can evaluate it deeply.

**Comment by mtmiller** [comment]
Right, if you check out the description of the `home` interface, the reason for this should stand out:

```
user@focal-virtualbox:~$ snap interface home
name:    home
summary: allows access to non-hidden files in the home directory
plugs:
  - docker
  - octave
slots:
  - snapd
```

Only non-hidden files and directories are available inside the snap. So try moving your mfiles to /home/ubuntu/mfiles or /home/ubuntu/Documents/mfiles.
