### ISSUE TITLE
Ghostscript not in container

### ISSUE THREAD

**Issue by PhilFreeman** [octave-snap/octave-snap#49]
When using octave from the CLI, unable to use the full capability of ```print()``` since ghostscript is not part of the container.

```
octave:2> surf(peaks)
octave:3> print('peaks.png')
warning: print.m: Ghostscript binary is not available.  Only eps output is possible
warning: called from
    __print_parse_opts__ at line 487 column 7
    print at line 416 column 8
error: print: cannot open file peaks.png for writing
error: called from
    print at line 428 column 7
```

Ghostscript is a fairly standard part of many automated workflows that use Octave to generate graphics/plots, and it should be part of the isntalled container.

**Comment by PhilFreeman** [comment]
Actually, that wasn't really the problem. I'll dig a little more and call this closed.

**Comment by PhilFreeman** [comment]
The above example isn't great. The issue is there, so I'm reopening this.

Launching octave as 'octave-cli' results in not being able to print figures because of missing Ghostscript. Ghostscript binary is an important part of a fully working Octave installation and should be part of the package. Many existing octave integration modules (notably octave_kernel for Jupyter notebooks) rely on passing commands to the CLI.

```
octave:1> surf(peaks)
octave:2> print('peaks.png')
warning: print.m: Ghostscript binary is not available.  Only eps output is possible
warning: called from
    __print_parse_opts__ at line 487 column 7
    print at line 416 column 8
error: __ghostscript__.m: Ghostscript binary is required for specified output format, but binary is not available in PATH
error: called from
    __ghostscript__ at line 64 column 5
    __opengl_print__ at line 155 column 29
    print at line 710 column 16
```

**Comment by mtmiller** [comment]
Yes, looks like a good thing to include. Might as well bundle epstool in there too.
