### ISSUE TITLE
removable-media plug

### ISSUE THREAD

**Issue by JonathanFolstein** [octave-snap/octave-snap#51]
It would be really helpful if you could add removable-media as a plug to the octave snap. Installing the snap worked great for ubuntu 18.04 lts, but I can't access any files outside my home directory and my computer just isn't set up that way. I need to connect to another drive using the removable-media interface and there appears to be no way to add the interface myself.  Excuse me if my terminology isn't perfect here, I'm new to snaps, but I'm pretty sure removable-media needs to be added to the snap by the developers.

thanks!
-jrf

**Comment by narrenschip** [comment]
Second that.

Octave is pretty useless if you can't access any data. (/home is NOT the location to mount network shares, local RAID arrays, ...)

**Comment by atudorb** [comment]
I also think it would be a useful plug to have for the octave snap package.

**Comment by barisdemiroz** [comment]
I have to switch computers and the easiest way to carry large amount of data is via an external disk. This would be very useful.

**Comment by athulkrishna2015** [comment]
yes, for me I wand to access files in external drive 
apt install octave works
