### ISSUE TITLE
Graphics Toolkit gnuplot not available

### ISSUE THREAD

**Issue by PhilFreeman** [octave-snap/octave-snap#52]
Both fltk and qt use OpenGL as the plotting back end. OpenGL has a known bug in using single precision for plotting, resulting in horrible plots of precision data (see bug #43782 for a good example). This is a known bug since at least 2012. The known workaround (it appears) is to use gnuplot as the graphics toolkit. However, this doesn't appear to be part of the snap package. Please add Gnuplot to the Octave Snap package.

Is there a way to install recent versions of Octave without using Snap? That would fix this too since I could then add whatever auxiliary packages/applications are needed without needing someone to bundle it in a container.

**Comment by mtmiller** [comment]
Another better known workaround is to scale your data series so you're not plotting large values with relatively tiny variations.

So gnuplot does appear to be in the snap, it just probably needs some symlinks and environment variables to get it working in its chrooted location.

The executable is on PATH as `gnuplot-qt`, and needs some other config to find the helper executables at `$SNAP/usr/lib/gnuplot`.

**Comment by PhilFreeman** [comment]
How do I plot the scaled and centered data, while preserving the axis labels so that units make sense? While scaling and centering may help with the rendering, it won't actually create plots that properly communicate the data. In the problem I'm working on now, GPS tracks.

Can you help explain how to configure gnuplot if it is already in the container? This isn't something I'm familiar with.

**Comment by mtmiller** [comment]
You can use the `xticklabels` and `yticklabels` functions to set the axis labels to be whatever you want regardless of the data scale.

For configuring gnuplot, I'm not suggesting it's something that a user should do, I'm suggesting it's something that can probably be fixed in the snap so it works by default.
