### ISSUE TITLE
help load produces error Can't locate Data/Dumper.pm in @INC ...

### ISSUE THREAD

**Issue by kdvolder** [octave-snap/octave-snap#54]
I reported this to octave, but they referred me here as it assumed to be an issue in snap packaging rather than a problem with octave itself.

The details of the error are as follows:

```
>> help load
Can't locate Data/Dumper.pm in @INC (you may need to install the Data::Dumper module) (@INC contains: /usr/lib/texinfo /snap/octave/30/usr/bin/../share/texinfo/lib/Unicode-EastAsianWidth/lib /snap/octave/30/usr/bin/../share/texinfo/lib/libintl-perl/lib /snap/octave/30/usr/bin/../share/texinfo /snap/octave/30/usr/bin/../share/texinfo /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /snap/octave/30/usr/bin/../share/texinfo/Texinfo/Common.pm line 2427.
BEGIN failed--compilation aborted at /snap/octave/30/usr/bin/../share/texinfo/Texinfo/Common.pm line 2427.
Compilation failed in require at /snap/octave/30/usr/bin/makeinfo line 110.
BEGIN failed--compilation aborted at /snap/octave/30/usr/bin/makeinfo line 110.
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of helptext follows...
'load' is a built-in function from the file libinterp/corefcn/load-save.cc
Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.
Help and information about Octave is also available on the WWW
at https://www.octave.org and via the help@octave.org
mailing list.
```

See here for the original report:

https://savannah.gnu.org/bugs/?59579

**Comment by mtmiller** [comment]
Thanks, this is the right place to report.

I can't reproduce this with Octave installed from the snap store on my system.

Have you tried uninstalling and reinstalling? The Data::Dumper module is present and working for my tests.

**Comment by kdvolder** [comment]
I didn't actually install this snap package via snap, but via 'sudo apt ...'. But apparantly it installs a snap package anyway. Maybe this is some weird repackaged snap package from Ubuntu? I'll try later on to uninstall it and then re-install directly as a snap package and let you know if that solves the problem.

**Comment by kdvolder** [comment]
For reference, the instructions I used for installing it came from here: https://wiki.octave.org/Octave_for_Debian_systems

So I basically just did what it says there: 

```
sudo apt-get install octave
```

**Comment by mtmiller** [comment]
That may be, but you also have the snap installed, and that takes precedence. Your choice, but if you want to make sure, try running `/usr/bin/octave --gui` versus `/snap/bin/octave --gui` and let us know which one or both reports the texinfo error.

**Comment by kdvolder** [comment]
I removed all traces of octave and then did `snap install octave` and now when I do 'help load' it works fine.
So however it was installed before, must have had some installation issue.

Snap package is working fine now though so I'll close this. Thanks for your time and help.
