### ISSUE TITLE
pkg install -forge [package] unable to get packages

### ISSUE THREAD

**Issue by Jules-Robotise** [octave-snap/octave-snap#6]
`pkg install -forge control `
=> 
```
error: get_forge_pkg: could not read URL, please verify internet connection
     error: called from
     get_forge_pkg at line 66 column 7
     get_forge_download at line 26 column 14
     pkg at line 407 column 31
```

jwe proposed to test : ` s = urlread ("ftp://ftp.octave.org/pub/README")`
=> 
`error: urlread: Couldn't resolve host name`

jwe proposed to test : system("gcc -v")
=>
`gcc -verror: 'gcc' undefined near line 1 column 1octave:1> system("gcc -v")Using built-in specs.COLLECT_GCC=gccCOLLECT_LTO_WRAPPER=/snap/octave/5/usr/bin/../lib/gcc/x86_64-linux-gnu/7/lto-wrapperOFFLOAD_TARGET_NAMES=nvptx-noneOFFLOAD_TARGET_DEFAULT=1Target: x86_64-linux-gnuConfigured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnuThread model: posixgcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) ans = 
`

**Comment by mtmiller** [comment]
Thanks, so the root issue seems to be that `urlread` isn't working for you in the snap environment. I can't reproduce this, so it may be something about the host system. Are you on Ubuntu or another distro, what version? Can you check the audit log for AppArmor denials?

**Comment by mtmiller** [comment]
Confirmed on Ubuntu, likely solution is to simply add the `network` plug. Testing in an Ubuntu VM now.
