### ISSUE TITLE
fix up more compiler and linker variables

### ISSUE THREAD

**Issue by mtmiller** [octave-snap/octave-snap#75]
A few compiler and linker variables are currently overridden in mkoctfile only to allow oct files to build. Let's expand the list and also fix them in the generated build-env.cc source file.

* `CFLAGS`
* `CPPFLAGS`
* `CXXFLAGS`
* `LDFLAGS`
* `OCT_LINK_OPTS`

While we're at it, remove the extra space in `CFLAGS`, `CPPFLAGS`, etc, when the value from the environment is empty. And add `-z now` to the linker flags.

**Comment by mmuetzel** [comment]
I was thinking that the flags in build-env.cc would be documenting the flags that were used on the build system (not necessarily the same flags that would be needed on the host system).
But I might be misunderstanding. Could you please clarify?

**Comment by mtmiller** [comment]
Sure. The specific options that I'm trying to undo are the `-I` and `-L` options that snapcraft automatically injects into the build environment, that don't make sense once the snap is built. In the stable version, which doesn't have this fix yet:

```
$ /snap/bin/octave --eval "__octave_config_info__ CXXFLAGS" 2>/dev/null
ans = -g -O2 -fstack-protector-strong  -isystem/root/parts/octave/install/usr/include -isystem/root/parts/octave/install/usr/include/x86_64-linux-gnu
```

As to why I'm now patching build-env.cc in addition to mkoctfile.cc, just for consistency, to have the same OCTAVE_CONF_* values in both places. When we're not cross-compiling, they normally do have the same value, so I'm trying to preserve that property.

**Comment by mmuetzel** [comment]
Ah. Thanks for explaining! 👍
