### ISSUE TITLE
octave-cli installs as octave.octave-cli

### ISSUE THREAD

**Issue by dgnorton** [octave-snap/octave-snap#8]
I'm running Ubuntu 18.04 and installed the `IOctave` kernel for JupyterLab. When `jupyter lab` is run it gives `OSError: octave-cli not found, please see README`. It appears that it is installed as `octave.octave-cli`.

```
❯ which octave-cli       
octave-cli not found

❯ which octave.octave-cli
/snap/bin/octave.octave-cli

❯ ls -l /snap/bin/octav* 
lrwxrwxrwx 1 root root 13 Oct 21 21:56 /snap/bin/octave -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Oct 21 21:56 /snap/bin/octave.octave-cli -> /usr/bin/snap
```
I don't have experience with how snaps work, other than installing them. It appears all "apps" are symlinks to the `snap` command. I'm guessing it looks at `arg[0]` and looks in a config somewhere to map that to the actual command? I tried the hacky solution of creating a symlink from `octave-cli` to `snap` - didn't work.

Is there a Docker container available that will build Linux binaries that I could manually install?

**Comment by dgnorton** [comment]
[This workaround](https://github.com/octave-snap/octave-snap/issues/9#issuecomment-546768497) solved two problems I had with the Octave snap.

**Comment by mtmiller** [comment]
Thanks, this would definitely be good to fix.

**Comment by mtmiller** [comment]
So this feature is called "aliases" in the snap packaging world, users can add aliases as needed, for example

    snap alias octave.octave-cli octave-cli

solves this locally.

To make this change automatic for every user, I need to request the alias from the snap store admins.

**Comment by mtmiller** [comment]
https://forum.snapcraft.io/t/request-for-octave-cli-alias/13915?u=mtmiller

**Comment by mtmiller** [comment]
Fixed in the Snap store now
