### ISSUE TITLE
feature request: Include rapidjson in edge channel

### ISSUE THREAD

**Issue by mmuetzel** [octave-snap/octave-snap#88]
Octave 7 adds new functions to import and export json encoded objects. This implementation is based on the rapidjson header-only library.
It looks like those headers weren't available when Octave was built for the edge channel.
E.g. when running the test suite with `__run_test_suite__`:
```
  libinterp/corefcn/jsondecode.cc-tst ............................ pass    0/0
                                                 (missing feature) SKIP    1
  libinterp/corefcn/jsonencode.cc-tst ............................ pass    0/0
                                                 (missing feature) SKIP    2
[...]
  fixed/json/jsondecode_BIST.tst ................................. pass    0/0
                                                 (missing feature) SKIP   34
  fixed/json/jsonencode_BIST.tst ................................. pass    0/0
                                                 (missing feature) SKIP   52
```

Would it be possible to add rapidjson as a build dependency for the edge channel?

**Comment by mtmiller** [comment]
Yeah, absolutely. I caught the recent Qhull change, but I may have missed other new dependencies on the development branch.

**Comment by mtmiller** [comment]
I probably missed it because configure doesn't warn about it, just filed [bug#60610](https://savannah.gnu.org/bugs/?60610) upstream.
