### ISSUE TITLE
Octave can't run curl

### ISSUE THREAD

**Issue by dgnorton** [octave-snap/octave-snap#9]
I originally opened [this issue](https://savannah.gnu.org/bugs/?57095) and wanted to continue the discussion here.

Octave is a programming language and I think it should be up to the end user running a program (not the compiler, interpreter, or packager) to decide whether it's trusted. E.g., a user that doesn't trust an Octave, Python, etc. script could easily run it sandboxed in a container. It should also be easy for that user to run their own or other trusted scripts without restrictions.

If there's a way for users like me to un-sandbox the Octave snap after installation, that would be fine but I couldn't find a way to do that.

**Comment by dgnorton** [comment]
For anyone that stumbles into this issue, another workaround that worked for me was: 
- Export env vars:
```
export OCTAVE_VERSION=5.1.0
export OCTAVE_VERSION=$OCTAVE_VERSION
export OCTAVE_HOME=~/octave
export LD_LIBRARY_PATH=$OCTAVE_HOME/lib/octave/$OCTAVE_VERSION
export PATH=$OCTAVE_HOME/bin:$PATH
```
- `wget https://octave-snapshot.s3.amazonaws.com/public/octave-$OCTAVE_VERSION-ubuntu-bionic-amd64.tar.xz`
- extract to a directory
- add that directory/bin to the PATH
- run `octave` then `sudo apt install <missing package>` until `octave` and `octave-cli` run successfully. List of dependencies can be [found here](https://gitlab.com/mtmiller/docker-octave/blob/master/Dockerfile).

**Comment by mtmiller** [comment]
Leaving this open for discussion, but at the moment it seems to me that strict confinement is the best and most portable option for distributing Octave as a snap.

**Comment by anonymouse64** [comment]
Note that for curl specifically, you can just package curl inside the snap.

**Comment by dgnorton** [comment]
According to [this](https://snapcraft.io/docs/snap-confinement?utm_source=insights&utm_campaign=snapd_2_20_classic_post), installing with `--classic` should override `strict` confinement but I tested with both `--classic` and `--devmode`. Neither allowed running `system('curl -V')`.

I don't think bundling `curl` inside the snap is the right direction. `curl` is just one example.

It's up to you if you want to close this issue. I have a workable solution that I will probably stick with even if the snap package is changed. In my opinion, the larger issue is that containers are great for certain uses but not as the default packaging for desktop apps.

**Comment by mtmiller** [comment]
From that page:

> Overriding a strictly confined snap with --classic is not recommended. This undoes the confinement and causes unpredictable behaviour.

You were right at the start, it's not possible for a user to switch confinement, the snap has to be built a certain way.

I don't think this is really the place to discuss whether or not confinement is a good thing for packaging desktop apps, that's more of a general snap philosophy discussion.

And I still consider apt to be the default packaging system, not sure about others.

**Comment by anonymouse64** [comment]
> installing with --classic should override strict confinement

Unfortunately that page is incorrect, providing the `--classic` flag does _not_ put a strictly confined application into classic confinement. See:

```
$ sudo snap install hello-world --classic
Warning: flag --classic ignored for strictly confined snap hello-world

hello-world 6.4 from Canonical✓ installed
``` 

> it's not possible for a user to switch confinement, the snap has to be built a certain way.

Correct.

**Comment by mtmiller** [comment]
I am leaning towards including curl in the Octave snap, simply because it is small and a simple solution. Also because it is included in other Octave containers I maintain (docker, flatpak), and might reasonably be considered part of a minimal core.

**Comment by dgnorton** [comment]
As a point of reference, I started using Octave as part of the Coursera
Machine Learning course. It's an extremely popular class and it recommends
using either Octave or Matlab Online. They have some boilerplate Octave
code that uses `curl` to submit assignments. When that fails, the refer
users to a few debugging threads in their forum but beyond that the
recommendation is switching to Matlab Online. If there's interest in
growing the Octave community, making the snap work out of the box for that
class is probably worth doing.

**Comment by mtmiller** [comment]
@dgnorton Thanks for the context, very appreciated. I agree with everything you've said.

It would also be nice if we could help the Coursera folks to update their scripts to use built-in functions like `urlread` or `webread` instead of shelling out to curl. Do you know if there's a way to report bugs, patches, or feedback to Coursera on their own scripts?

**Comment by dgnorton** [comment]
I don't know but I will check.
